---
- name: Install consul agent and nginx
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure APT is updated
      ansible.builtin.apt:
        update_cache: true

    - name: Install dependencies, and nginx
      ansible.builtin.apt:
        name:
          - wget
          - gpg
          - nginx
        state: present

    - name: Copy the index file
      ansible.builtin.template:
        src: templates/index.j2
        dest: /var/www/html/index.html
        mode: "0644"
      vars:
        servername: web01

    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: restarted

    - name: Download HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashicorp.gpg
        mode: "0644"
        force: false  # Prevents re-downloading if the file already exists

    - name: Add HashiCorp GPG key to keyring
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
              https://apt.releases.hashicorp.com \
              {{ ansible_distribution_release | lower }} main"
        state: present
        filename: hashicorp

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Consul
      ansible.builtin.apt:
        name: consul
        state: present

    - name: Copy Consul server settings
      ansible.builtin.template:
        src: templates/consul-agent.hcl.j2
        dest: /etc/consul.d/consul.hcl
        mode: "0644"
      vars:
        datacenter: dc1
        data_dir: /opt/consul
        server: "false"
        bind_addr: 192.168.33.20
        encrypt: "/Ryxixfgry4++HPab6Zq9I3jakehUwN9CeJqgHCj1+Y="
        enable_script_checks: "true"
        leave_on_terminate: "true"
        retry_join: 192.168.33.10

    - name: Copy the settings to register nginx
      ansible.builtin.template:
        src: templates/consul-webserver.hcl.j2
        dest: /etc/consul.d/webserver.hcl
        mode: "0644"
      vars:
        consul_name: webserver
        consul_port: 80
        check_args_method: curl
        check_args_addr: localhost
        check_interval: 3s

    - name: Enable and start Consul service
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: restarted
        no_block: true
