Vagrant.configure("2") do |config|

  config.vm.define "consul" do |consul|
    consul.vm.box = "ubuntu/jammy64"
    consul.vm.hostname = "consul"
    consul.vm.network "public_network", ip: "192.168.33.10"
    consul.vm.network "forwarded_port", guest: 8500, host: 8500

    consul.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y ansible
    SHELL
    
    consul.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/consul-server.yml"
      ansible.compatibility_mode = "2.0"
     end

    consul.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "public_network", ip: "192.168.33.20"

    web01.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y ansible
    SHELL
    
    web01.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/web01.yml"
      ansible.compatibility_mode = "2.0"
    end

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/jammy64"
    web02.vm.hostname = "web02"
    web02.vm.network "public_network", ip: "192.168.33.30"

    web02.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y ansible
    SHELL
    
    web02.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/web02.yml"
      ansible.compatibility_mode = "2.0"
    end

    web02.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/jammy64"
    lb.vm.hostname = "lb"
    lb.vm.network "public_network", ip: "192.168.33.40"

    lb.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install -y ansible
    SHELL
    
    lb.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbooks/lb.yml"
      ansible.compatibility_mode = "2.0"
    end
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end
end
